version: '3.5'
services:
  oidc:
    image: ${DOCKER_REGISTRY:-nmro}/business/security/oidc
    build:
      context: .
      dockerfile: business/security/Oidc/Dockerfile
    volumes:
      - ./devops/certs/self-signed/oidc/oidc.nmro.local.pfx:/app/oidc.nmro.local.pfx:ro
    depends_on:
      - monorepo
      - consul

  iam-api:
    image: ${DOCKER_REGISTRY:-nmro}/services/iam-api
    build:
      context: .
      dockerfile: business/security/IAM/Faces/Api/Dockerfile
    environment:
      - ConnectionStrings__IamDbConnection=${PGDB_IAM:-Server=db-postgres;port=5432;Database=iam_db;UserId=nmro_dbadmin;Password=theForest&;Pooling=true}
    depends_on:
      - monorepo
      - consul
  iam-worker:
    image: ${DOCKER_REGISTRY:-nmro}/services/iam-worker
    build:
      context: .
      dockerfile: business/security/IAM/Faces/Worker/Dockerfile
    environment:
      - ConnectionStrings__IamDbConnection=${PGDB_IAM:-Server=db-postgres;port=5432;Database=iam_db;UserId=nmro_dbadmin;Password=theForest&;Pooling=true}
      - ConnectionStrings__HangfireConnection=${PGDB_HANGFIRE:-Server=db-postgres;port=5432;Database=hangfire_db;UserId=nmro_dbadmin;Password=theForest&;Pooling=true}
    depends_on:
      - monorepo
