version: '3.5'
services:
  consul:
    command: agent -server -bootstrap-expect 1 -ui -client 0.0.0.0
    ports:
      - 53:53/udp
      - 8500:8500
  proxy:
    ports:
      - 80:80
      - 443:443
    environment:
      PUBLIC_ORIGIN: ${PUBLIC_ORIGIN:-nmro.local}
    command: /bin/sh -c "envsubst '$$PUBLIC_ORIGIN' < /etc/nginx/domains.template > /etc/nginx/nginx.conf && exec nginx-debug -g 'daemon off;'"
    volumes:
      - ./Gateways/ReverseProxy/config/domains.template:/etc/nginx/domains.template:ro
      - ./Gateways/ReverseProxy/html:/etc/nginx/html:ro

  oidc:
    networks:
      default:
        aliases:
          - oidc.${PUBLIC_ORIGIN:-nmro.local}

  apigateway:
    networks:
      default:
        aliases:
          - api.${PUBLIC_ORIGIN:-nmro.local}

  landing:
    environment:
      IdentityUrl: http://oidc.${PUBLIC_ORIGIN:-nmro.local}
      CallBackUrl: http://${PUBLIC_ORIGIN:-nmro.local}

  health:
    environment:
      IdentityUrl: http://oidc.${PUBLIC_ORIGIN:-nmro.local}
      HealthChecksUI__Webhooks__Uri: "https://${LS_NOTIFY_HOOK}"

  iam-api:
    environment:
      - ConnectionStrings__DefaultConnection=${DB_POSTGRES:-Server=db-postgres;port=5432;Database=iam_db;UserId=nmro_dbadmin;Password=theForest&;Pooling=true}

networks:
  default:
    name: nmro-network
    driver: bridge
