version: '3.5'
services:
  slnbased:
    image: slnbased
    build:
      context: .
      dockerfile: Bblocks/SlnBased/Dockerfile

  oidc:
    networks:
      default:
        aliases:
          - oidc.${PUBLIC_ORIGIN:-nmro.local}

  apigateway:
    networks:
      default:
        aliases:
          - api.${PUBLIC_ORIGIN:-nmro.local}

networks:
  default:
    name: nmro-network
    driver: bridge
