version: '3.5'

services:
  consul:
    image: ${DOCKER_REGISTRY:-nmro}/service-discovery
    build:
      context: .
      dockerfile: Discovery/Dockerfile

  proxy:
    image: ${DOCKER_REGISTRY:-nmro}/proxy
    build:
      context: .
      dockerfile: Gateways/ReverseProxy/Dockerfile
    depends_on:
      - consul
      - oidc
      - apigateway
      - landing

  slnbased:
    image: nmro-based
    build:
      context: .
      dockerfile: BuildingBlocks/SlnBased/Dockerfile

  oidc:
    image: ${DOCKER_REGISTRY:-nmro}/oidc
    build:
      context: .
      dockerfile: Services/Oidc/Dockerfile
    depends_on:
      - consul
      - slnbased

  landing:
    image: ${DOCKER_REGISTRY:-nmro}/landing
    build:
      context: .
      dockerfile: Web/Landing/Dockerfile
    depends_on:
      - slnbased
      - consul

  health:
    image: ${DOCKER_REGISTRY:-nmro}/health
    build:
      context: .
      dockerfile: Web/Health/Dockerfile
    depends_on:
      - consul
      - slnbased

  apigateway:
    image: ${DOCKER_REGISTRY:-nmro}/apigateway
    build:
      context: .
      dockerfile: Gateways/ApiGateway/Dockerfile
    depends_on:
      - slnbased
      - consul

  iam-api:
    image: ${DOCKER_REGISTRY:-nmro}/api/iam
    build:
      context: .
      dockerfile: Services/IAM/Dockerfile
    depends_on:
      - slnbased
      - consul
