version: '3.5'
services:
  db-postgres:
    image: ${DOCKER_REGISTRY:-nmro}/postgres
    build:
      context: .
      dockerfile: foundation/backings/postgres/Dockerfile
    volumes:
      - db-postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  db-redis:
    image: ${DOCKER_REGISTRY:-nmro}/redis
    build:
      context: .
      dockerfile: foundation/backings/redis/Dockerfile
    ports:
      - 6379:6379

  redis-cmd:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=docker:db-redis:6379
      - URL_PREFIX=/redis

volumes:
  db-postgres:
  db-redis:
