version: '3.5'
services:
  db-postgres:
    image: ${DOCKER_REGISTRY:-nmro}/postgres
    build:
      context: .
      dockerfile: DevOnly/Postgres/Dockerfile
    volumes:
      - db-postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-postgres:
