version: '3.5'
services:
  db-postgres:
    image: ${DOCKER_REGISTRY:-nmro}/postgres
    build:
      context: .
      dockerfile: DevOnly/Postgres/Dockerfile
    volumes:
      - db-postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  db-redis:
    image: ${DOCKER_REGISTRY:-nmro}/redis
    build:
      context: .
      dockerfile: DevOnly/Redis/Dockerfile
    volumes:
      - ./DevOnly/Redis/redis.conf:/usr/local/etc/redis/redis.conf
  
volumes:
  db-postgres:
  db-redis:
