version: '3'

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms256m"
    networks:
      - netmicro

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./logstash/templates:/usr/share/logstash/templates:ro
    ports:
      - "5000:5000"
      - "5000:5000/udp"
      - "5001:5001/udp"
      - "5002:5002/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      LS_OUTPUT_SLACK: $LS_OUTPUT_SLACK
    privileged: true
    networks:
      - netmicro
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - netmicro
    depends_on:
      - elasticsearch

  apm-server:
    build:
      context: extensions/apm-server/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./apm-server/config/apm-server.yml:/usr/share/apm-server/config/apm-server.yml:ro
    ports:
      - "8200:8200"
    networks:
      - netmicro
    depends_on:
      - elasticsearch

  curator:
    build:
      context: extensions/curator/
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      CRON: 0 0 * * *
      CONFIG_FILE: /usr/share/curator/config/curator.yml
      COMMAND: /usr/share/curator/config/delete_log_files_curator.yml
      UNIT_COUNT: 8
    networks:
      - netmicro
    depends_on:
      - elasticsearch

  logspout:
    build:
      context: extensions/logspout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      ROUTE_URIS: logstash://logstash:5000
      LOGSTASH_TAGS: docker-netmicro
    networks:
      - netmicro
    depends_on:
      - logstash
    restart: on-failure

volumes:
  esdata:
    driver: local

networks:
  netmicro:
    driver: bridge
