actions:
  1:
    action: delete_indices
    description: >-
      Delete logstash-docker indice which less than ${UNIT_COUNT} days old. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-docker-
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: ${UNIT_COUNT}
      exclude:
  2:
    action: delete_indices
    description: >-
      Delete apm-7.3.0-onboarding indice which less than ${UNIT_COUNT} days old. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: apm-7.3.0-onboarding-
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: ${UNIT_COUNT}
      exclude:
