version: '3.5'
services:
  oidc:
    image: ${DOCKER_REGISTRY:-nmro}/services/oidc
    build:
      context: .
      dockerfile: Services/Oidc/Dockerfile
    depends_on:
      - slnbased
      - consul

  iam-api:
    image: ${DOCKER_REGISTRY:-nmro}/services/iam-api
    build:
      context: .
      dockerfile: Services/IAM/API/Dockerfile
    environment:
      - ConnectionStrings__IamDbConnection=${DB_POSTGRES:-Server=db-postgres;port=5432;Database=iam_db;UserId=nmro_dbadmin;Password=theForest&;Pooling=true}
    depends_on:
      - slnbased
      - consul
  iam-async-worker:
    image: ${DOCKER_REGISTRY:-nmro}/services/iam-async-worker
    build:
      context: .
      dockerfile: Services/IAM/Workers/AsyncWorker/Dockerfile
    environment:
      - ConnectionStrings__IamDbConnection=${DB_POSTGRES:-Server=db-postgres;port=5432;Database=iam_db;UserId=nmro_dbadmin;Password=theForest&;Pooling=true}
      - ConnectionStrings__HangfireConnection=${DB_POSTGRES:-Server=db-postgres;port=5432;Database=hangfire_db;UserId=nmro_dbadmin;Password=theForest&;Pooling=true}
    depends_on:
      - slnbased
