version: '3.5'
services:
  oidc:
    image: ${DOCKER_REGISTRY:-nmro}/services/oidc
    build:
      context: .
      dockerfile: Services/Oidc/Dockerfile
    depends_on:
      - slnbased
      - consul

  iam-api:
    image: ${DOCKER_REGISTRY:-nmro}/services/iam-api
    build:
      context: .
      dockerfile: Services/IAM/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=${DB_POSTGRES:-Server=db-postgres;port=5432;Database=iam_db;UserId=nmro_dbadmin;Password=theForest&;Pooling=true}
    depends_on:
      - slnbased
      - consul
