---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
elasticsearch.hosts: http://elasticsearch:9200
apm_oss.indexPattern: apm-*
apm_oss.errorIndices: apm-*
apm_oss.onboardingIndices: apm-*
apm_oss.spanIndices: apm-*
apm_oss.transactionIndices: apm-*