## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.js
#
server.name: kibana
server.host: "0"

server.basePath: /elk
server.rewriteBasePath: false

elasticsearch.hosts: [http://elasticsearch:9200]
xpack.monitoring.ui.container.elasticsearch.enabled: true

## X-Pack security credentials
#
elasticsearch.username: elastic
elasticsearch.password: changeme

apm_oss.indexPattern: apm-7.6.0-*
apm_oss.errorIndices: apm-7.6.0-*
apm_oss.onboardingIndices: apm-7.6.0-*
apm_oss.spanIndices: apm-7.6.0-*
apm_oss.transactionIndices: apm-7.6.0-*
apm_oss.metricsIndices: apm-7.6.0-*
apm_oss.sourcemapIndices: apm-7.6.0-*
