version: '3.5'

services:
  proxy:
    image: ${DOCKER_REGISTRY:-nmro}/proxy
    build:
      context: .
      dockerfile: Reverseproxy/Dockerfile
    depends_on: 
      - oidc
      - apigateway
      - website
    networks: 
      - nmro-network

  oidc:
    image: ${DOCKER_REGISTRY:-nmro}/oidc
    build:
      context: .
      dockerfile: Services/Oidc/Dockerfile
    networks: 
      - nmro-network

  website:
    image: ${DOCKER_REGISTRY:-nmro}/website
    build:
      context: .
      dockerfile: Website/Dockerfile
    networks: 
      - nmro-network

  apigateway:
    image: ${DOCKER_REGISTRY:-nmro}/apigateway
    build:
      context: .
      dockerfile: Gateways/ApiGateway/Dockerfile
    networks:
      - nmro-network

  iam-api:
    image: ${DOCKER_REGISTRY:-nmro}/api/iam
    build:
      context: .
      dockerfile: Services/IAM/Dockerfile
    networks:
      - nmro-network
    ports: 
      - 8080:80

networks:
  nmro-network:
    driver: bridge