version: '3.5'
services:
  landing:
    image: ${DOCKER_REGISTRY:-nmro}/web/landing
    build:
      context: .
      dockerfile: Web/Landing/Dockerfile
    environment:
      IdentityUrl: http://oidc.${PUBLIC_ORIGIN:-nmro.local}
      CallBackUrl: http://${PUBLIC_ORIGIN:-nmro.local}
    depends_on:
      - slnbased
      - consul

  health:
    image: ${DOCKER_REGISTRY:-nmro}/web/health
    build:
      context: .
      dockerfile: Web/Health/Dockerfile
    environment:
      IdentityUrl: http://oidc.${PUBLIC_ORIGIN:-nmro.local}
      HealthChecksUI__Webhooks__Uri: "https://${LS_NOTIFY_HOOK}"
    depends_on:
      - slnbased
      - consul
